NAME = tsp

NAME1 = 1tsp

SRC = tsp.c

SRC1 = tsp1.c

all: $(NAME) $(NAME1)

$(NAME): $(SRC)
	cc -Wall -Wextra -Werror -lm $(SRC) -o $(NAME)

$(NAME1): $(SRC1)
	cc -Wall -Wextra -Werror -lm $(SRC1) -o $(NAME1)