#!/usr/bin/python3

import argparse
import sys

def get_args():
    parser = argparse.ArgumentParser()
    group = parser.add_mutually_exclusive_group(required = True)
    group.add_argument('-g', action='store', dest='g')
    group.add_argument('-k', action='store', dest='k')
    args = parser.parse_args()
    if (len(sys.argv) < 3):
        return (args, True)
    if (len(sys.argv[2]) < 1):
        return (args, True)
    return (args, False)

def print_args():
    print(f'{"cmd":8}: {sys.argv[1][1]}')
    print(f'{"link":8}: {sys.argv[2]}')

def process_and_store_key(hexa_key):

def generate_temp_password(key_file):

def main():
    args, empty_args = get_args()
    if (not empty_args):
        print_args()
    else:
        return
    if (sys.argv[1][1] == 'g'):
        process_and_store_key(args.g)
    else:
        generate_temp_password(args.k)
    
    

if __name__ == "__main__":
    main()